export const browserSupportedColors: Record<string, string> = {
  black: 'black',
  green: 'green',
  yellow: 'yellow',
  white: 'white',
  purple: 'purple',
  red: 'red',
  gold: 'gold',
  silver: 'silver',
  coral: 'coral',
  blue: 'blue',
  pink: 'pink',
  'rose-gold': 'peachpuff',
  midnight: 'midnightblue',
  'space-black': 'dimgray',
  'space-gray': 'gray',
  graphite: 'darkgray',
  midnightgreen: 'cadetblue',
  'sierra-blue': 'lightsteelblue',
};
